spring.application.name=fitness-app
spring.datasource.url=jdbc:mysql://localhost:3306/fitness_db?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

logging.level.com.zaxxer.hikari=WARN
logging.level.org.springframework.jdbc=DEBUG
